# Generated by Django 4.1.3 on 2022-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50, verbose_name='categoria')),
            ],
        ),
    ]
