# Generated by Django 4.1.3 on 2022-12-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100, verbose_name='nombre_proveedor')),
                ('telefono_proveedor', models.CharField(max_length=30, verbose_name='telefono_proveedor')),
                ('segundo_telefono', models.CharField(default=None, max_length=30, verbose_name='telefono_proveedor')),
                ('direccion_proveedor', models.CharField(max_length=100, verbose_name='direccion_proveedor')),
                ('observacion', models.CharField(default=None, max_length=500, verbose_name='observacion')),
            ],
        ),
    ]
