# Generated by Django 4.1.3 on 2022-12-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(default=None, max_length=255, verbose_name='nombre_proveedor')),
                ('categoria', models.CharField(default=None, max_length=255, verbose_name='categoria')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='nombre_producto')),
                ('medidas', models.CharField(default=None, max_length=255, verbose_name='medidas')),
                ('costo', models.BigIntegerField(default=0, verbose_name='costo')),
                ('tiempo_entrega', models.IntegerField(null=True, verbose_name='tiempo_entrega')),
                ('nota', models.CharField(max_length=255, null=True, verbose_name='nota')),
                ('id_categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias')),
                ('id_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
        ),
    ]
