# Generated by Django 4.1.3 on 2022-12-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_factura', models.IntegerField(null=True, verbose_name='id_factura')),
                ('nombre_proveedor', models.CharField(max_length=100, null=True)),
                ('fecha_despacho', models.CharField(max_length=50, null=True)),
                ('fecha_pago', models.CharField(max_length=50, null=True)),
                ('valor', models.BigIntegerField(default=0, verbose_name='valor')),
                ('pagada', models.BooleanField(null=True, verbose_name='pagada')),
                ('nota', models.CharField(max_length=500, null=True)),
                ('id_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
        ),
    ]
