# Generated by Django 4.1.3 on 2022-12-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_facturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadores',
            fields=[
                ('id_transportador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_transportador', models.CharField(max_length=100, null=True, verbose_name='nombre_transportador')),
                ('telefono_transportador', models.CharField(max_length=50, null=True, verbose_name='telefono_transportador')),
                ('cedula_transportador', models.CharField(max_length=50, null=True, verbose_name='cedula_transportador')),
                ('direccion_transportador', models.CharField(max_length=100, null=True, verbose_name='direccion_transportador')),
                ('nombre_contacto_emergencia', models.CharField(max_length=100, null=True, verbose_name='nombre_contacto_emergencia')),
                ('numero_contacto_emergencia', models.CharField(max_length=100, null=True, verbose_name='numero_contacto_emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id_vendedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_vendedor', models.CharField(max_length=100, null=True, verbose_name='nombre_vendedor')),
                ('telefono_vendedor', models.CharField(max_length=25, null=True, verbose_name='telefono_vendedor')),
                ('cedula_vendedor', models.CharField(max_length=25, null=True, verbose_name='cedula_vendedor')),
                ('correo_vendedor', models.CharField(max_length=100, null=True, verbose_name='correo_vendedor')),
                ('direccion_vendedor', models.CharField(max_length=100, null=True, verbose_name='direccion_vendedor')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre_contacto_emergencia', models.CharField(max_length=100, null=True, verbose_name='nombre_contacto_emergencia')),
                ('numero_contacto_emergencia', models.CharField(max_length=100, null=True, verbose_name='numero_contacto_emergencia')),
            ],
        ),
    ]
