# Generated by Django 4.1.3 on 2022-12-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_transportadores_vendedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=250, null=True, verbose_name='cedula_vendedor')),
                ('cedula_cliente', models.CharField(max_length=250, null=True, verbose_name='correo_vendedor')),
                ('direccion_cliente', models.CharField(max_length=250, null=True, verbose_name='direccion_cliente')),
                ('ciudad_cliente', models.CharField(max_length=250, null=True, verbose_name='ciudad_cliente')),
                ('correo_cliente', models.CharField(max_length=250, null=True, verbose_name='correo_cliente')),
                ('telefono_cliente', models.CharField(max_length=250, null=True, verbose_name='telefono_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_venta', models.IntegerField(null=True, verbose_name='id_venta')),
                ('nombre_vendedor', models.CharField(default=None, max_length=150, verbose_name='nombre_vendedor')),
                ('fecha_venta', models.CharField(max_length=50, null=True, verbose_name='telefono_vendedor')),
                ('nombre_cliente', models.CharField(max_length=150, null=True, verbose_name='nombre_cliente')),
                ('cedula_cliente', models.CharField(max_length=50, null=True, verbose_name='cedula_cliente')),
                ('fecha_entrega', models.CharField(max_length=50, null=True, verbose_name='numero_contacto_emergencia')),
                ('entregado', models.BooleanField(null=True, verbose_name='numero_contacto_emergencia')),
                ('valor_venta', models.BigIntegerField(null=True, verbose_name='valor_venta')),
                ('abono', models.BigIntegerField(default=0, verbose_name='abono')),
                ('saldo', models.BigIntegerField(null=True, verbose_name='saldo')),
                ('id_cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.clientes')),
                ('id_vendedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255, null=True, verbose_name='nombre_categoria')),
                ('valor', models.BigIntegerField(null=True, verbose_name='valor')),
                ('disponible', models.BooleanField(null=True, verbose_name='disponible')),
                ('nota', models.CharField(max_length=255, null=True, verbose_name='nota')),
                ('id_factura', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.facturas')),
                ('id_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('id_autogenerado', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_remision', models.IntegerField(null=True, verbose_name='id_remision')),
                ('nombre_transportador', models.CharField(max_length=150, null=True, verbose_name='nombre_transportador')),
                ('productos_entregados', models.CharField(max_length=2500, null=True, verbose_name='productos_entregados')),
                ('fecha_remision', models.CharField(max_length=50, null=True, verbose_name='fecha_remision')),
                ('nota', models.CharField(max_length=2000, null=True, verbose_name='nota')),
                ('id_transportador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.transportadores')),
                ('id_venta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_orden_pedido', models.IntegerField(null=True, verbose_name='id_orden_pedido')),
                ('valor_total', models.BigIntegerField(null=True, verbose_name='valor_total')),
                ('tela', models.CharField(max_length=250, null=True, verbose_name='tela')),
                ('fecha', models.CharField(max_length=250, null=True, verbose_name='fecha')),
                ('fecha_despacho', models.CharField(max_length=250, null=True, verbose_name='fecha_despacho')),
                ('enviada', models.CharField(max_length=250, null=True, verbose_name='fecha_despacho')),
                ('recibida', models.BooleanField(null=True, verbose_name='recibida')),
                ('id_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
                ('id_vendedor', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='inventario.vendedores')),
                ('id_venta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas')),
            ],
        ),
    ]
