# Generated by Django 4.1.3 on 2022-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_clientes_ventas_stock_remisiones_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='enviada',
            field=models.BooleanField(max_length=250, null=True, verbose_name='enviada'),
        ),
    ]
